### ISSUE TITLE
Add build/reload request

### ISSUE THREAD

**Issue by adpi2** [build-server-protocol/build-server-protocol#134]
The ability to trigger a build server refresh is currently missing from the protocol.

This issue is a follow up of https://github.com/sbt/sbt/issues/5783. Adding a `build/reload request ` will ease the integration between IntelliJ and sbt, as well as IntelliJ and Bloop.

Basically,
- `workspace/buildTargets` is safe and returns the latest known state of the build
- `build/reload` asks the server to refresh the state of the build but it can fail, in which case the server might stop responding

A typical scenario would be:
- the user changes the build configuration file then clicks the `reload` button
- a `build/reload` request is sent by the client to the server
- the server reload the configuration
- after reloading successfully it replies with a success response
- the client sends a `workspace/buildTargets` request to ask the new list of build targets

**Comment by jastice** [comment]
I am writing up the spec and protocol implementation right now!

Relevant spec parts:

```ts
export interface BuildServerCapabilities {
[...]
      /** Reloading the build state through workspace/reload is supported */
  canReload?: Boolean
```

```
### Reload request

The `reload` request instructs the build server to reload the build configuration.
This request should be supported by build tools that keep their state in memory.
If the `reload` request returns with an error, it's expected that other requests 
respond with the previously known "good" state.

Request:

- method: `workspace/reload`
- params: `null`

Response:

- result: `null`
- error: code and message in case an error happens during reload. For example, 
when the build configuration is invalid
```

Subject to change with reviews of course.

**Comment by jastice** [comment]
to discuss: shoudl it be `workspace/reload` or `build/reload`

**Comment by adpi2** [comment]
Ok great, this is good!

I like `build/reload` better than `workspace/reload` because it is part of the server lifetime category with:
- `build/initialize`
- `build/shutdown`
- `builld/exit`

**Comment by adpi2** [comment]
I let you finish the implementation :)
