### ISSUE TITLE
[Proposal] - Can we add a `DebugAdaptorProvider` (or something similiar) into the BuildServerCapabilities?

### ISSUE THREAD

**Issue by ckipp01** [build-server-protocol/build-server-protocol#145]
While working on sbt BSP integration in Metals, I came a across a use case that having something like `DebugAdaptorProvider` or something similar in `BuildServerCapabilities` would have been quite useful. I noticed that in the https://github.com/build-server-protocol/build-server-protocol/pull/135 a `canReload` was added which is useful for the client to check to see if the server implements it before requesting it. In Metals we generate code lenses to trigger debug runs, and after seeing the reload pr my instinct was to check to see if the build server was a DAP provider via checking the `BuildServerCapabilities` before generating them. However, looking at https://github.com/build-server-protocol/build-server-protocol/pull/99 it seems that wasn't part of the pr.

Would it be possible to adapt the spec a bit to include something like this for clients to ensure a build server implements it before sending in a `debugSession/start`?

**Comment by tgodzik** [comment]
I agree this would be very useful, especially with more BSP servers being created.

**Comment by jastice** [comment]
Yup, this shouldn't be a big problem to add, since there's only one implementation I think?

**Comment by er1c** [comment]
I noticed that `debugSession/start`, while the messages are defined in code: https://github.com/build-server-protocol/build-server-protocol/blob/master/bsp4s/src/main/scala/ch/epfl/scala/bsp/endpoints/Endpoints.scala#L72  There is no mention of it in the specification.  Is this related, or a separate issue than this ticket?

**Comment by er1c** [comment]
I added a PR for this, please review!
