### ISSUE TITLE
[Proposal] - A way to signify a no-op compilation

### ISSUE THREAD

**Issue by ckipp01** [build-server-protocol/build-server-protocol#148]
In [Metals](https://scalameta.org/metals/) we treat compilations a bit differently on whether or not we mark them as "no-ops". If a compilations is no-op it allows us to skip certain things in the editor UX such as refreshing the tree view. You can see a bit of this [logic here](https://github.com/scalameta/metals/blob/8f1c5db0e76ddbb95db06a55afc395ca6a965d13/metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala#L117-L148) if you're curious. We currently detect this when using Bloop by reaching into the `buid/taskStart` message to see if it contains a `Start no-op compilation`. You can see where this is marked in [Bloop here](https://github.com/scalacenter/bloop/blob/4768184cc8842d5d6773646ccda93210a89f1b05/frontend/src/main/scala/bloop/reporter/BspProjectReporter.scala#L301-L331).

When we recently added support for sbt BSP, we obviously wanted to continue this distinction between _normal_ compilation and a _no-op_ compilation. However, that's hard to do when we're just relying on it being in a message. This lead me to wonder if it'd be a possibility to just bake this into the spec somehow as I can see how it'd be useful to have for various editors to determine what type of compilation task is taking place. I'm not sure where a logical place for this would actually be, but figured I'd throw the idea out there to see what others thought.

**Comment by jastice** [comment]
I think a natural place would be an optional field in `CompileReport` or `CompileResult`, depending on whether you want to handle this on a whole-compile or target level
