### ISSUE TITLE
Exclude compilation artifacts from searchable files

### ISSUE THREAD

**Issue by julienrf** [build-server-protocol/build-server-protocol#205]
IDEs usually provide a fast search feature, which allows you to search for some text in all the source files of your project. In the case of sbt projects, sbt generates a lot of small files in the `target/` directory. When we import a project via BSP in an IDE, these compilation artifacts (the content of `target/`) are included in the scope of a search, making it slow, and showing irrelevant results.

I think the developer experience would be improved if we introduced a concept of paths excluded from the actual sources of the project, that IDEs could leverage.

Currently, importing a project in IntelliJ via the sbt import feature does exclude the `target/` directories, but this is not the case when we import the same project via the BSP import feature (so, the sbt import does not suffer from this issue).

---

Here is a concrete example. I did `sbt new scala/scala3.g8`, and then imported the project (which uses sbt 1.5.5) in IntelliJ.

By default, IntelliJ imports the project via sbt, and the `target/` directory is excluded from the indexed files, as you can see here:

![Screenshot from 2021-07-30 11-16-01](https://user-images.githubusercontent.com/332812/127631601-81459351-1d7e-4680-b16c-0e4fcf28928e.png)

Then, if I re-import the project via BSP, the `target/` directory is not anymore excluded (it’s interesting to see that `project/target/` is excluded, though…):

![Screenshot from 2021-07-30 11-20-23](https://user-images.githubusercontent.com/332812/127631687-46c00ba8-312c-461e-8d24-51c2acd1d221.png)

As a consequence, when I search something, IntelliJ also searches in the `target/` directory:

![Screenshot from 2021-07-30 11-22-07](https://user-images.githubusercontent.com/332812/127631984-a7f567fd-47e9-492c-94b7-59c300e4e380.png)

Logs: [bsp-protocol-trace-2021-07-30T11-17-14.log](https://github.com/build-server-protocol/build-server-protocol/files/6906486/bsp-protocol-trace-2021-07-30T11-17-14.log)

**Comment by adpi2** [comment]
To me it looks like an issue in sbt or IntelliJ rather than an issue with BSP. Because, the `target/` directory should never be included in the `buildTarget/sources` response, nor in the `buildTarget/resources`.

```
[Trace - 10:44:36 AM] Received response 'buildTarget/sources - (3)' in 131ms
Result: {
  "items": [
    {
      "target": {
        "uri": "file:/home/piquerez/scalacenter/hello-world/#hello-world/Compile"
      },
      "sources": [
        {
          "uri": "file:/home/piquerez/scalacenter/hello-world/src/main/scala/",
          "kind": 2,
          "generated": false
        },
        {
          "uri": "file:/home/piquerez/scalacenter/hello-world/src/main/scala-2.13",
          "kind": 2,
          "generated": false
        },
        {
          "uri": "file:/home/piquerez/scalacenter/hello-world/src/main/scala-2",
          "kind": 2,
          "generated": false
        },
        {
          "uri": "file:/home/piquerez/scalacenter/hello-world/src/main/java",
          "kind": 2,
          "generated": false
        }
      ]
    },
{
      "target": {
        "uri": "file:/home/piquerez/scalacenter/hello-world/#hello-world/Test"
      },
      "sources": [
        {
          "uri": "file:/home/piquerez/scalacenter/hello-world/src/test/scala",
          "kind": 2,
          "generated": false
        },
        {
          "uri": "file:/home/piquerez/scalacenter/hello-world/src/test/scala-2.13",
          "kind": 2,
          "generated": false
        },
        {
          "uri": "file:/home/piquerez/scalacenter/hello-world/src/test/scala-2",
          "kind": 2,
          "generated": false
        },
        {
          "uri": "file:/home/piquerez/scalacenter/hello-world/src/test/java",
          "kind": 2,
          "generated": false
        }
      ]
    },
}
```

**Comment by julienrf** [comment]
I think it’s the responsibility of BSP to inform the IDEs about the files that should be excluded from indexing.

If BSP is used by the IDEs to import the projects, they need a way to know which files should be indexed, and which files should be excluded. I don’t see how an IDE could guess which files should be excluded since it depends of the underlying build tool, and BSP’s role is precisely to be the layer between IDEs and build tools.

For instance, we probably want `README.md` to be indexed, but we clearly don’t want any file from `target/` (except for managed sources) to be indexed.

**Comment by adpi2** [comment]
Actually it seems that IntelliJ exclude the `classes` and `test-classes` from the `target` directory.

![image](https://user-images.githubusercontent.com/13123162/127670370-40795c55-5d96-4b7d-8924-6f2911a25ba6.png)

It knows that because the `classDirectory` is in the `ScalacOptionsItems`:

```
{
      "target": {
        "uri": "file:/home/piquerez/scalacenter/hello-world/#root/Test"
      },
      "options": [
        "-Xplugin:/home/piquerez/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.3/4.4.24/semanticdb-scalac_2.13.3-4.4.24.jar",
        "-P:semanticdb:sourceroot:/home/piquerez/scalacenter/hello-world",
        "-P:semanticdb:targetroot:/home/piquerez/scalacenter/hello-world/target/scala-2.13/meta",
        "-Yrangepos",
        "-P:semanticdb:synthetics:on",
        "-P:semanticdb:failures:warning",
        "-P:semanticdb:targetroot:/home/piquerez/scalacenter/hello-world/target/scala-2.13/test-meta"
      ],
      "classpath": [
        "file:/home/piquerez/scalacenter/hello-world/target/scala-2.13/classes/",
        "file:/home/piquerez/scalacenter/hello-world/target/scala-2.13/test-classes/",
        "file:/home/piquerez/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.3/scala-library-2.13.3.jar"
      ],
      "classDirectory": "file:/home/piquerez/scalacenter/hello-world/target/scala-2.13/test-classes/"
    }
```

Similarly we could have an `outputDirectory` in the `BuildTarget` that would be excluded form indexing.

**Comment by olafurpg** [comment]
I think it would be nice if BSP had a notion of declaring what directories should be excluded from the IDE. I recall that the Pants IntelliJ plugin works around this limitation by manually excluding Bloop directories when using Pants via BSP. It would be more natural if the protocol had a notion of "exclude directories", which can cover more broad directories like `target/` instead of only excluding the classes directories.

**Comment by povder** [comment]
This PR will fix this issue for the protocol itself: https://github.com/build-server-protocol/build-server-protocol/pull/269. Then, this sbt PR https://github.com/sbt/sbt/pull/6985 and intellij-scala PR https://github.com/JetBrains/intellij-scala/pull/627 will fix the problem for IntelliJ IDEA users.
