### ISSUE TITLE
Diagnostic out of sync with LSP

### ISSUE THREAD

**Issue by ckipp01** [build-server-protocol/build-server-protocol#319]
Hello! I have a couple questions on the current format of `Diagnostic`. Currently in the BSP specification it says

> where Diagnostic is defined as it is in LSP.

This was probably true when BSP was first defined, but LSP has added a few more things to the LSP [`Diagnostic`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnostic). Just to name a few, `codeDescription`, `tags`, `data`. I'd like to know if the desire is to keep the BSP diagnostic in sync with the LSP diagnostic or to provide a minimal interpretation of it? I think it might be a good idea to mimic it, and if so I'd be happy to pr those changes in. If not, I can update the docs to notify users that it is different. If that is the case I'd like to propose that at least `codeDescription` be added in.

Another point is the `DiagnosticRelatedInformation`. I see that in the BSP implementation [here](https://github.com/build-server-protocol/build-server-protocol/blob/master/bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/Diagnostic.java) that `relatedInformation` is just something that exists or doesn't, but is a single instance rather than a list of them like the LSP spec has them. I'm not sure if this was oversight or if there was a specific reason for this, but I was wondering if this could be aligned with the spec as well? I've been slowly working on [a plan](https://contributors.scala-lang.org/t/revisiting-dotty-diagnostics-for-tooling/5649) to expose more structured information in diagnostics, and part of that is utilizing `DiagnosticRelatedInformation`. The hope would be that these could be included right in [`xsbti.Problem`](https://github.com/sbt/sbt/discussions/6868) and then easily reported via BSP.  However, the use cases that I have for it have multiple different `relatedInformation`s that would need to be included with a diagnostic, which is currently impossible.

**Comment by jastice** [comment]
> I'd like to know if the desire is to keep the BSP diagnostic in sync with the LSP diagnostic or to provide a minimal interpretation of it? I think it might be a good idea to mimic it, and if so I'd be happy to pr those changes in. If not, I can update the docs to notify users that it is different. If that is the case I'd like to propose that at least codeDescription be added in.

I think it would be fine to add in the additional data if we have any use case for it. Regardless, it seems like a good idea to explicitly specify the format of diagnostics rather than offhandedly refering to LSP spec.

> Another point is the DiagnosticRelatedInformation. I see that in the BSP implementation [here](https://github.com/build-server-protocol/build-server-protocol/blob/master/bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/Diagnostic.java) that relatedInformation is just something that exists or doesn't, but is a single instance rather than a list of them like the LSP spec has them. I'm not sure if this was oversight or if there was a specific reason for this, but I was wondering if this could be aligned with the spec as well?

I think it's an oversight, or perhaps LSP spec changed? I don't think it's currently used anywhere, but probably better to align it before you do use it.

**Comment by ckipp01** [comment]
Didn't realize this was still open. Closed as of #320.
