### ISSUE TITLE
Handle Cancellation

### ISSUE THREAD

**Issue by tgodzik** [build-server-protocol/build-server-protocol#365]
In LSP each request can be responded with a cancel:
```
[Trace - 01:20:07 PM] Received notification '$/cancelRequest'
Params: {
  "id": 200
}
```

However, it seems nothing like this was ever introduced into BSP proper, so there is no way to cancel a long running compilation.

The question is, should we handle it? Or maybe it's handled and I just wasn't doing something correctly?

**Comment by jastice** [comment]
I thought it's handled by virtue of extending lsp4j? IIRC requests can be canceled, or did you try it and it didn't work?

**Comment by tgodzik** [comment]
I would think so also, but maybe we are doing something wrong :thinking: I will double check.

**Comment by tgodzik** [comment]
Yep, my bad. A lost conversion from Java to Scala future was losing the cancelable.
