### ISSUE TITLE
A Changelog is missing

### ISSUE THREAD

**Issue by lefou** [build-server-protocol/build-server-protocol#430]
Or maybe, I was not able to find it. I looked in the following places:

* Github repo: there is no changelog file and no such section in the Readme
* Github Release Pages: There are no published GH Release pages since `2.0.0-M16`
* Documentation: The documentation site does not list any changes and also no `since` attributes to any newer part of the protocol
* Github Milestones: There are no current GH milestones associated with issues and pull requests

It would be very nice to have a changelog, so users of the protocol can follow, which changes and additions happened at which released version. Thanks!

**Comment by ckipp01** [comment]
Hey @lefou, thanks for brining this up. This should absolutely be doable.

Since I don't really see any release process in the contributing docs or know when we decide to cut a release or not, I think it'd be a good idea to document this and ensure that a changelog/release notes on GitHub are created.

**Comment by lefou** [comment]
Hm, I don't see a reasonable changelog in latest release 2.1.0-M5. There is a GitHub Release entry with a list of merged pull requests, which is mostly dependency updates. What I'm looking for is what has changed to the protocol and what is necessary/optional to do, when updating my BSP integration to this version.

**Comment by ckipp01** [comment]
> Hm, I don't see a reasonable changelog in latest release 2.1.0-M5. There is a GitHub Release entry with a list of merged pull requests, which is mostly dependency updates. What I'm looking for is what has changed to the protocol and what is necessary/optional to do, when updating my BSP integration to this version.

I've gone ahead and update the release with some more details. Hopefully that's sufficient.

**Comment by lefou** [comment]
> > Hm, I don't see a reasonable changelog in latest release 2.1.0-M5. There is a GitHub Release entry with a list of merged pull requests, which is mostly dependency updates. What I'm looking for is what has changed to the protocol and what is necessary/optional to do, when updating my BSP integration to this version.
> 
> I've gone ahead and update the release with some more details. Hopefully that's sufficient.

Great! Thank you!
