### ISSUE TITLE
Introducing JavaBuildTarget

### ISSUE THREAD

**Issue by jdneo** [build-server-protocol/build-server-protocol#473]
Now the JVM Build Target defined Java Home path and its version.

While for a project, it may have other JDK related configurations like `source compatibility` and `target compatibility` level.

Should we consider add them to the definition of JVM Build Target? Or is there any other way to expose that information in current definition of BSP?

**Comment by adpi2** [comment]
> Should we consider add them to the definition of JVM Build Target? Or is there any other way to expose that information in current definition of BSP?

Technically it would be possible to add them in the definition of JVM build target, or we could add another request/capability in the JVM extension. I guess it depends if your use-case is universal enough: does it apply to almost all build tools/IDEs of the JDK world or only a few of them.

How do you get those `source compatibility` and  `target compatibility` level in your build tool? How can it be used by BSP clients?

**Comment by jdneo** [comment]
> How do you get those source compatibility and target compatibility level in your build tool?

Take Gradle and Java as an example, they can be fetched as a property of the `JavaCompile` task. - https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.JavaCompile.html#org.gradle.api.tasks.compile.JavaCompile:sourceCompatibility

> How can it be used by BSP clients?

Consider a Java project using JDK 17 with source compatibility level set to 11. The client can use it to decide which set of language features should be provided. For example, although JDK 17 supports the `record` keyword, it should not be available when the source compatibility is set to 11.

**Comment by adpi2** [comment]
It seems `source compatibiliy` is Java specific, while `target compatibility` can be used in other JVM languages (the `-release` of the Scala compiler).

So I would propose this:
- add an optional `targetCompatibility` field in the `JVMBuildTarget`
- create a Java target in the Java extension with an optional `sourceCompatibility` field. The `JavaBuildTarget` should "extend" the `JVMBuildTarget`:
```ts
export interface JavaBuildTarget {
  sourceCompatibility?: Int;

  jvmBuildTarget: JvmBuildTarget;
}
```

**Comment by jdneo** [comment]
Thank you for the response @adpi2.

I have a question. The spec says:

```
JvmBuildTarget is a basic data structure that contains jvm-specific metadata, specifically JDK reference. This metadata is embedded in the data: Option[Json] field of the BuildTarget definition, when the dataKind field contains "jvm".
```

If we introduce `JavaBuildTarget`, what `dataKind` should we fill then? Still use `jvm`?

**Comment by adpi2** [comment]
> If we introduce JavaBuildTarget, what dataKind should we fill then? Still use jvm?

It would then be `java`

**Comment by jdneo** [comment]
> It would then be java

I see. Thank you @adpi2!

**Comment by jdneo** [comment]
Rethink about this issue, I've changed my opinion on this. Reason:

1. Is `source compatibility` a related concept of `build`? My answer to this question now is `No`. Since build server is more focus on build, `source compatibility` looks like not related with it.
2. The document of `javaVersion` says: `The java version this target is supposed to use.` I think this is exactly the target level, which means `targetCompatibility` is not necessary either.
