### ISSUE TITLE
Clarifying BSP Specification: Servers should send `build/publishDiagnostics` with empty array to clear former diagnostics?

### ISSUE THREAD

**Issue by tanishiking** [build-server-protocol/build-server-protocol#481]
### Describe the use-case for this feature

In the LSP specification, LSP servers are required to send [textDocument/publishDiagnostics](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_publishDiagnostics) with an empty array of diagnostics to clear any previously published diagnostics.

> If the computed set is empty, the server must push an empty array to clear former diagnostics.
> https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_publishDiagnostics

However, the BSP specification does not provide clear guidance on how to clear previously published diagnostics, which has led to some confusion:

- A BSP client (scalameta/metals) expects to receive [build/publishDiagnostics](https://build-server-protocol.github.io/docs/specification/#publish-diagnostics) with an empty diagnostics array (and reset = true).
- Some BSP servers, such as sbt and bloop, do send build/publishDiagnostics with an empty array of diagnostics when the computed set is empty.
- Yet, other BSP servers, like [bazel-bsp](https://youtrack.jetbrains.com/issue/BAZEL-376) and [mill-bsp](https://github.com/com-lihaoyi/mill/issues/2426), do not follow this practice.

### What do you propose

So, I propose there is a need to clarify how BSP clients should clear former diagnostics.

Should servers send `build/publishDiagnostics` with empty diagnostics, or should clients clear former diagnostics upon receiving a [build/taskFinish](https://build-server-protocol.github.io/docs/specification/#compile-request) with both errors and warnings set to 0?

### I've checked to make sure there isn't already a way to support this in the current protocol

- [X] I've checked the existing protocol and there isn't a way to do this currently

### Maintainer approval (This is for the maintainers)

- [x] Jetbrains
- [x] Metals
- [x] Scala Center

**Comment by jastice** [comment]
Yes, the behavior of sbt and bloop was our informal agreement back then. I think we should follow the LSP practice in how it works, and be explicit about expected behavior.
