### ISSUE TITLE
Support clean request

### ISSUE THREAD

**Issue by jdneo** [build-server-protocol/build-server-protocol#509]
### Describe the use-case for this feature

A lot of build tools have the concept of clean the generated files. Like the `clean` command in Maven/Gradle/SBT.

It looks like there is no dedicated request for this scenario.

Use case:

- When do incremental build, use 1 compile request.
- When do a full build, use clean + compile request.

### I've checked to make sure there isn't already a way to support this in the current protocol

- [X] I've checked the existing protocol and there isn't a way to do this currently

### Maintainer approval (This is for the maintainers)

- [ ] Jetbrains
- [ ] Metals
- [x] Scala Center

**Comment by tgodzik** [comment]
There is already https://build-server-protocol.github.io/docs/specification#clean-cache-request which is related, not sure if the same.

**Comment by jdneo** [comment]
@tgodzik Oh, I thought that was to clean the status of language server itself. After re-reading the spec, looks like that was what I want. Thank you!
