### ISSUE TITLE
The type flaws in the protocol

### ISSUE THREAD

**Issue by ShuiRuTian** [build-server-protocol/build-server-protocol#521]
1. Prefer use primitive types rather than boxed type

Please refer: https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#general-types
I suggest to replace 'String' with 'string', and also for Boolean or anything mentioned in the link...

2. Use integer rather than Integer, or define Integer
This is a really small flaw, more like typo.
The integer type defined in LSP is 'integer', refer https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#baseTypes 

3. `Long` is not defined
This is bit worse than `Integer`, because this type is not defined!

4. Some types are not defined
Like this
``` ts
export interface TestParams {
  // ...

  /** Kind of data to expect in the `data` field. If this field is not set, the kind of data is not specified. */
  dataKind?: String;

  /** Language-specific metadata about for this test execution.
   * See ScalaTestParams as an example. */ // This is also strange, because I could not find ScalaTestParams in search of the website
  data?: TestParamsData; // HERE, the type "TestParamsData;" is lacked
}
export namespace TestParamsDataKind { // And this type is not used at all.
  /** `data` field must contain a ScalaTestParams object. */
  export const ScalaTest = "scala-test";
}
```

And this happens for nearly all `data?: XXXX`

Seems we want to express that the implementation could give the data whatever they like.

Then I suggest to replace the design with:
``` ts
export interface TestParams {
  // ...

  /** Language-specific metadata about for this test execution. */
  data?: TestParamsData;
}

export interface TestParamsData{
  kind: TestParamsDataKind;
  [key: string]: any;
}

export type TestParamsDataKind = string;

export namespace TestParamsDataKind {
  /** `data` field must contain a ScalaTestParams object. */
  export const ScalaTest = "scala-test";
}
```

And I suggest more strict constraint to the name of TestParamsDataKind, like `${language_name}-test`.

5. Wrong use of namespace in typescript

Well, although I understand the intention is like "includes but not limited". And it's much more important to understand the design rather than flaws like this, it's not correct to write something like
``` ts
namespace Foo{
export const foo1 = "123"
}
interface Bar{
  foo: Foo; // ts will complains about this in fact.
}
```

You need to define Foo firstly:

``` ts
type Foo = string;
namespace Foo{
export const foo1 = "123"
}
interface Bar{
  foo: Foo; // Good now
}
```

Just like what I suggested in the fourth point  :)

**Comment by abrams27** [comment]
thanks a lot!
about the 4th point: https://github.com/build-server-protocol/build-server-protocol/discussions/487 there are plans to change the `dataType` / `data` mechanizm in the 3.0 release

**Comment by agluszak** [comment]
Thanks @ShuiRuTian! I already started fixing the problems you mentioned. In general we recently started *generating* the specification (and the TS definitions) from the Smithy model, but the generator is still imperfect :)
