### ISSUE TITLE
bsj4j-2.1.0-M6 dropped support for Java 8

### ISSUE THREAD

**Issue by lefou** [build-server-protocol/build-server-protocol#619]
I wonder whether this is on purpose or not? The release documentation, especially the section about breaking changes, does not mention that Java 8 is no longer supported. Is there some technical reason for it? Would it be possible to re-add support for Java 8? E.g. by using a Java 8 VM to run the publish job in GitHub CI/CD.

Mill 0.11 as well as current Metals still support Java 8, which means both projects can't integrate newer bsp4j version. AFAIK, that are two of the three main consumers (server API). 

* https://github.com/com-lihaoyi/mill/pull/2794
* https://github.com/scalameta/metals/pull/5664

**Comment by agluszak** [comment]
@lefou  https://github.com/build-server-protocol/build-server-protocol/releases/tag/v2.1.0-M7

**Comment by lefou** [comment]
Great news, thanks!
