### ISSUE TITLE
2.1.0 isn't published / strange artifact grouping

### ISSUE THREAD

**Issue by kubukoz** [build-server-protocol/build-server-protocol#644]
### Describe the use-case for this feature

I'm trying to pull the spec-traits module. I didn't see any coordinates in the README or on the website, so I went to sbt to check them, and to my surprise everything is under the `ch.epfl.scala` org directly:

```
sbt:build-server-protocol> show organization
[info] bsp4s / organization
[info]  ch.epfl.scala
[info] spec / organization
[info]  ch.epfl.scala
[info] bsp4j / organization
[info]  ch.epfl.scala
[info] tests / organization
[info]  ch.epfl.scala
[info] codegen / organization
[info]  ch.epfl.scala
[info] spec-traits / organization
[info]  ch.epfl.scala
[info] docs / organization
[info]  ch.epfl.scala
[info] bsp-testkit / organization
[info]  ch.epfl.scala
[info] organization
[info]  ch.epfl.scala
sbt:build-server-protocol> show name
[info] bsp4s / name
[info]  bsp4s
[info] spec / name
[info]  spec
[info] bsp4j / name
[info]  bsp4j
[info] tests / name
[info]  tests
[info] codegen / name
[info]  codegen
[info] spec-traits / name
[info]  spec-traits
[info] docs / name
[info]  docs
[info] bsp-testkit / name
[info]  bsp-testkit
[info] name
[info]  build-server-protocol
```

and indeed, things like `spec-traits` are available under that org via Coursier:

```
cs complete-dep ch.epfl.scala:spec-traits:01:44:16
2.2.0-M1+6-fedeba89-SNAPSHOT
2.1.0-M5
2.1.0-M6-alpha
2.1.0-M6
2.1.0-M7
2.2.0-M1.alpha
2.2.0-M1
```

I don't have any issue with that, although you might want to consider grouping some of these under `.bsp` or similar, because `ch.epfl.scala:spec` is pretty vague and doesn't immediately point to BSP.

However, I can't see `2.1.0` in the version list, and explicitly pulling it fails. Looks like 2.1.0 wasn't published correctly:

https://github.com/build-server-protocol/build-server-protocol/actions/runs/6826139499/job/18565394067

### What do you propose

- attempt a re-release of 2.1.0?
- drop a 2.1.1 that fixes the publishing?

additionally:
- switch orgs (at least for some artifacts)?

### I've checked to make sure there isn't already a way to support this in the current protocol

- [X] I've checked the existing protocol and there isn't a way to do this currently

### Maintainer approval (This is for the maintainers)

- [ ] Jetbrains
- [ ] Metals
- [x] Scala Center

**Comment by adpi2** [comment]
The release failed because there are two tags on the same commit: `v2.1.0-M5` and `v2.1.0`. I'll try to push an empty commit and move the `v2.1.0` tag to re-release.

**Comment by adpi2** [comment]
It's in progress: https://github.com/build-server-protocol/build-server-protocol/actions/runs/7567897476

**Comment by agluszak** [comment]
[It's been published](https://repo1.maven.org/maven2/ch/epfl/scala/bsp4j/2.1.0/), thank you @adpi2 for handling that, tbh I forgot about this one.

> switch orgs (at least for some artifacts)?

I think that yes, we could do that with BSP 3.0 release.

**Comment by adpi2** [comment]
`v2.1.0` was on the same commit as `v2.1.0-M5` and so it does not contain the changes from `v2.1.0-M7`. So I am releasing `v2.1.1` on top of `v2.1.0-M7`:

https://github.com/build-server-protocol/build-server-protocol/actions/runs/7608823379

ping @tgodzik
