### ISSUE TITLE
Information about transitive dependencies.

### ISSUE THREAD

**Issue by KristianAN** [build-server-protocol/build-server-protocol#679]
### Describe the use-case for this feature

Many build tools today can give detailed dependency graphs that show transitive dependencies, e.g. maven or sbt. Being able to forward this information through BSP to IDEs could very useful to create various useful tooling.

Example usecase: I want to create a security linter in my IDE that can show if a dependency has a reported cve or if a transitive dependency has a reported cve.

### What do you propose

An interface that provides a single function that returns a nested graph of dependencies. 

### I've checked to make sure there isn't already a way to support this in the current protocol

- [X] I've checked the existing protocol and there isn't a way to do this currently

### Maintainer approval (This is for the maintainers)

- [ ] Jetbrains
- [ ] Metals
- [ ] Scala Center

**Comment by adpi2** [comment]
We already have the [buildTarget/dependencyModules](https://build-server-protocol.github.io/docs/specification#buildtargetdependencymodules-request) request which returns a flat list of dependencies, including transitive dependencies. The extension for Maven dependencies is [here](https://build-server-protocol.github.io/docs/extensions/maven#dependencymoduledata-kinds).

Would that be enough for what you need.

**Comment by KristianAN** [comment]
> We already have the [buildTarget/dependencyModules](https://build-server-protocol.github.io/docs/specification#buildtargetdependencymodules-request) request which returns a flat list of dependencies, including transitive dependencies. The extension for Maven dependencies is [here](https://build-server-protocol.github.io/docs/extensions/maven#dependencymoduledata-kinds).
> 
> Would that be enough for what you need?

Yeah, I read through the spec, but somehow missed that. That is exactly what I am looking for :)
