### ISSUE TITLE
Documentation and github bsp version inconsistent with the released 2.0.0-M4 bsp

### ISSUE THREAD

**Issue by adadima** [build-server-protocol/build-server-protocol#92]
It seems like some of the more recent changes to bsp that are described in the documentation were not included in the 2.0.0-M4 release. One example is RunParams, which should have `data` and `dataKind` fields according to the most recent developments, but these do not appear in the distributed version.

**Comment by adadima** [comment]
Never mind, this was a problem on my end.

**Comment by jastice** [comment]
Seems to be fixed in current releases
