### ISSUE TITLE
Support for for environment variables in application invocation

### ISSUE THREAD

**Issue by propensive** [build-server-protocol/build-server-protocol#93]
It would be useful to be able to pass environment variables to an application invocation. For example,
```
trait RunParams {
  // ...
  def environment: Map[String, String]
}
```

**Comment by tgodzik** [comment]
@propensive I think this should be fixed in https://github.com/build-server-protocol/build-server-protocol/pull/118

**Comment by ckipp01** [comment]
I believe this can also be closed.
